### ISSUE TITLE
default conf is confusing

### ISSUE THREAD

**Issue by ghost** [qtoggle/qtoggleserver-rpigpio#1]
**Describe the bug:**
the default file from /data/etc/qtoggleserver.conf contains and old config port

`    {
        driver = "qtoggleserver.drivers.ports.gpio.GPIO"
        no = 10
    }
`
I think it should be `qtoggleserver.rpigpio.RPiGPIO`

**Comment by ccrisan** [comment]
It's actually a generic GPIO driver that's supposed to work on any board, not only on the Raspberry Pi.
